trigger:
  branches:
    include:
    - master
  paths:
    include:
    - app
    exclude:
    - iac
pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: Build
    jobs:
    - job: DockerBuild
      displayName: Docker Build
      steps:
      - task: Docker@2
        displayName: Build an image
        inputs:        
          command: build
          dockerfile: '**/Dockerfile'
          tags: |
            $(tag)
          arguments: -t wheel-dev-ecr:$(Build.BuildId)
      - task: ECRPushImage@1
        inputs:
          awsCredentials: 'CashPersonalAWS'
          regionName: 'us-east-2'
          imageSource: 'imagename'
          sourceImageName: 'rearc-quest'
          sourceImageTag: '$(Build.BuildId)'
          repositoryName: 'wheel-dev-ecr'
      - task: ECRPushImage@1
        inputs:
          awsCredentials: 'CashPersonalAWS'
          regionName: 'us-east-2'
          imageSource: 'imagename'
          sourceImageName: 'rearc-quest'
          sourceImageTag: '$(Build.BuildId)'
          repositoryName: 'wheel-dev-ecr'
          pushTag: '$(Build.BuildId)'
      
    